name: Build PHP Images

on:
#  push:
#    branches: [ main ]

  workflow_dispatch:
    inputs:
      php_version:
        description: 'PHP version to build (leave empty to build all versions)'
        required: false
        type: choice
        options:
          - ''
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'

jobs:
  build_and_push_php:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        version: ${{ inputs.php_version == '' && fromJSON('["7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]') || fromJSON(format('["{0}"]', inputs.php_version)) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.version }}-cli
        uses: docker/build-push-action@v4
        with:
          context: ./php/${{ matrix.version }}-cli
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hoopan/php:${{ matrix.version }}-cli

      - name: Build and push ${{ matrix.version }}-fpm
        uses: docker/build-push-action@v4
        with:
          context: ./php/${{ matrix.version }}-fpm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hoopan/php:${{ matrix.version }}-fpm

      - name: Build and push ${{ matrix.version }}-cli-alpine
        uses: docker/build-push-action@v4
        with:
          context: ./php/${{ matrix.version }}-cli
          file: ./php/${{ matrix.version }}-cli/Dockerfile-alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hoopan/php:${{ matrix.version }}-cli-alpine

      - name: Build and push ${{ matrix.version }}-fpm-alpine
        uses: docker/build-push-action@v4
        with:
          context: ./php/${{ matrix.version }}-fpm
          file: ./php/${{ matrix.version }}-fpm/Dockerfile-alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hoopan/php:${{ matrix.version }}-fpm-alpine
